### PR TITLE
Formalization of result 46 and update of result 37

### PR DESCRIPTION
**Pull request by fredericchardard**
This is an update of result 37 (cubic equation) and result 46 (quartic equation).
Both results are proved in the same file cardan_ferrari.v (hence cardan3.v is obsolete).
Changes are made accordingly in index.html and LICENSE files.

### CODE REVIEW

**Comment by palmskog** [comment]
To make CI pass, please edit `_CoqProject` to reflect the changed filename (`cardan_ferrari.v` instead of `cardan3.v`).

**Comment by fredericchardard** [comment]
I have changed _CoqProject and README.md files accordingly.

**Comment by palmskog** [comment]
This looks good to me, I can merge unless @jmadiot has comments?

**Comment by jmadiot** [comment]
Nice! @fredericchardard do you want me to change the date from "2017" to "2017-2020" in the .v's header license as well? (Or you can make a PR)

**Pull request merged**
